version: 0.0.{build}
clone_folder: C:\projects\Mezz_Foundation

image:
  - Visual Studio 2017

environment:
  matrix:
  - GENERATOR: Visual Studio 15 2017 Win64

configuration:
  - Debug
  - Release

before_build:
  # Stop useless Xamarin Build targets from making messages
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  # Finalize build prep
  - mkdir build
  - cd build
  - mkdir JagatiPackages
  - set JAGATI_DIR=C:\projects\Mezz_Foundation\build\JagatiPackages
  - echo "Current Configuration is '%CONFIGURATION%'"
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% .. -DMEZZ_BuildDoxygen=OFF

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: cd C:\projects\Mezz_Foundation\build
  - cmd: Foundation_Tester xml

notifications:
- provider: Email
  to:
  - contact@blacktoppstudios.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

